routes/web.php
<?php

use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Employee\ComplementController;
use App\Http\Controllers\Employee\InventoryController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\Employee\PackageController;
use App\Http\Controllers\Employee\ServiceController;
use App\Http\Controllers\Employee\StatusController;
use App\Http\Controllers\Employee\MenuController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PDFController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Website\MenuController as WebsiteMenuController;
use Illuminate\Support\Facades\Route;

// Route::get('/', function () {
//     return view('dashboard.dashAdmin', [DashboardController::class, 'dashboardAdmin']);
// });



Route::get('/reservar', [BookingController::class, 'create'])->name('website.reservar');
Route::post('/reservar', [BookingController::class, 'store'])->name('reservar.store');

Route::get('/factura', function () {
    return view('facturas.plantilla-pdf');
});

Route::get('/inicio', function () {
    return view('website/principal');
})->name('website');

#Visualizar vista verificar correo
#Route::get('/verify', function () {
    #return view('auth/verify');
#})->name('website');
#

Route::controller(MenuController::class)->group(function () {
    Route::match(array('GET', 'POST'), 'website/menu', [WebsiteMenuController::class,'index'])->name('website.menu');
    Route::match(array('GET', 'POST'), 'website/menu/search', [WebsiteMenuController::class,'search'])->name('website.menu.search');
    Route::match(array('GET', 'POST'), 'website/menu/category', [WebsiteMenuController::class,'searchByCategory'])->name('website.menu.category');
});


//Route::get('menu', function () {
//    return view('menu.index');
//});
//Route::get('menu/crear', function () {
//    return view('menu.crear');
//});
//Route::get('menu/ver', function () {
//    return view('menu.ver');
//});



//Route::resource('inventario', InventoryController::class);

//Route::get('inventario/{id}', [InventoryController::class, 'show']);



//Route::get('configuracion', function () {
//    return view('configuracion.index');
//});

// Route::get('create-pdf-file', [PDFController::class, 'index']);

//Authenticated Routes
Route::middleware(['auth'])->group( function () {
    Route::get('/profile/edit', 'App\Http\Controllers\ProfileController@edit')->name('profile.edit');
    Route::get('/profile/change-password', 'App\Http\Controllers\ProfileController@change_password')->name('profile.change-password');
    Route::get('/profile', 'App\Http\Controllers\ProfileController@index')->name('profile.index');
    Route::patch('/profile', 'App\Http\Controllers\ProfileController@update')->name('profile.update');
});

//Admin Routes
Route::prefix('admin')->name('admin.')->middleware(['auth', 'auth.isAdmin'])->group( function () {
    Route::resource('/users', UserController::class);
});

//Employee routes
Route::middleware(['auth', 'verified', 'auth.isEmployee'])->group( function () {
    //TODO: Empleados
    Route::get('/empleados', function () {
        return view('empleados.index');
    });
    Route::get('/empleados/crear', function () {
        return view('empleados.crear');
    });
    //TODO: Clientes
    Route::get('/clientes', function () {
        return view('clientes.index');
    });
    Route::get('/clientes/crear', function () {
        return view('clientes.crear');
    });
    Route::get('/clientes/ver', function () {
        return view('clientes.ver');
    });
    Route::get('/reportes', function () {
        return view('reportes.index');
    });
    Route::get('/updateStatus', [BookingController::class, 'updateStatus'])->name('update-status');

    Route::get('/dashboard', [DashboardController::class, 'dashboardAdmin']);

    Route::post('create-pdf-file', [PDFController::class, 'index']);

    Route::resource('/reservaciones', BookingController::class);
    Route::resource('/inventario', InventoryController::class);
    Route::resource('/status', StatusController::class);
    Route::resource('/services',ServiceController::class);
    Route::resource('/menus', MenuController::class);
    Route::resource('/packages', PackageController::class);
    Route::resource('/complements',ComplementController::class);
});

//Customer routes
Route::middleware(['auth', 'auth.isCustomer'])->group( function () {
    Route::get('/dashboard/customer', [DashboardController::class, 'dashboardCliente'])->name('dashboardCustomer');
});

//Default routes

Route::get('/', [HomeController::class, 'index']);

resources/views/reservaciones/index.blade.php
@extends('app')

@section('extra-css')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.4/css/dataTables.bootstrap5.min.css"/>
@endsection

@section('contenido')

<!--Page header-->
<div class="page-header d-xl-flex d-block">
    <div class="page-leftheader">
        <h4 class="page-title">Reservaciones</h4>
    </div>
    <div class="page-rightheader ml-md-auto">
        <div class="align-items-end flex-wrap my-auto right-content breadcrumb-right">
            <div class="btn-list">
                <a href="reservaciones/create" class="btn btn-primary mr-3">
                    <i class="feather  feather-plus sidemenu_icon"></i>
                    Agregar reservaciones</a>
            </div>
        </div>
    </div>
</div>
<!--End Page header-->

<!-- Row -->
<div class="row">
    @include('sweetalert::alert')
    <div class="col-xl-12 col-md-12 col-lg-12">
        <div class="card">
            <div class="card-header  border-0">
                <h4 class="card-title">Lista de Reservaciones</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    {{--DATATABLE--}}
                    <table class="table  table-vcenter text-wrap table-bordered border-bottom" id="project-list">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nombre del evento</th>
                                <th>Dirección</th>                                
                                <th>Fecha y hora</th>
                                <th>Cliente</th>
                                <th>Estado</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @isset($bookings)
                                @foreach ($bookings as $booking)
                                    <tr>
                                        <td>{{$booking->id}}</td>
                                        {{-- <td width="200px"> --}}
                                        <td>
                                            <span>{{$booking->name}}</span>
                                        </td>
                                        {{-- <td width="350px"> --}}
                                        <td>
                                            <span>{{$booking->address->street_name}}. México, {{$booking->address->zip_code}} Cd Victoria, Tamaulipas.</span>
                                        </td>
                                        <td>
                                            <div class="d-flex">
                                                <div class="mr-3 mt-0 mt-sm-1 d-block">
                                                    <h6 class="mb-1 fs-14"><span class="text-muted mb-0 fs-14">Fecha:</span>{{$booking->booking_date}}</h6>
                                                    <h6 class="mb-1 fs-14"><span class="text-muted mb-0 fs-14">Hora:</span> {{$booking->booking_time}}</h6>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="d-flex">
                                                <span class="avatar avatar-md brround mr-3" style="background-image: url({{asset('images/usuario.png')}}"></span>
                                                <div class="mr-3 mt-0 mt-sm-1 d-block">
                                                    <h6 class="mb-1 fs-14">{{$booking->user->name}}</h6>
                                                    <p class="text-muted mb-0 fs-12">{{$booking->user->email}}</p>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <select name="status" id="" onchange="updateEstatus(event);" data-id="{{$booking->id}}" class="badge bg-danger-transparent border border-danger">
                                                @foreach ($statuses as $status)
                                                @if ($status->id == $booking->status_id)
                                                    <option value="{{$status->id}}" selected>{{$status->name}}</option>
                                                @else
                                                    <option value="{{$status->id}}">{{$status->name}}</option>
                                                @endif
                                                @endforeach
                                            </select>
                                        </td>
                                        <td>
                                            <div class="d-flex">
                                                <a href="{{ route('reservaciones.show', $booking->id) }}" class="action-btns1" data-toggle="tooltip" data-placement="top" title="Ver"><i class="feather feather-eye text-primary"></i></a>
                                                <a href="{{ route('reservaciones.edit', $booking->id) }}" class="action-btns1" data-toggle="tooltip" data-placement="top" title="Editar"><i class="feather feather-edit-2  text-success"></i></a>
                                                <form action="{{route('reservaciones.destroy', $booking->id)}}" method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button class="action-btns1 feather feather-trash-2 text-danger show_confirm" data-toggle="tooltip" data-placement="top" title="Eliminar" type="submit"></button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            @endisset
                        </tbody>
                    </table>
                    {{--FIN DATATABLE--}}
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Row-->
@endsection

@section('extra-script')
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.11.4/js/dataTables.bootstrap5.min.js"></script>
{{--"url": "//cdn.datatables.net/plug-ins/1.11.3/i18n/es-MX.json"//ES = 90% and MX 88% //cdn.datatables.net/plug-ins/1.11.4/i18n/es-MX.json--}}
<script type="text/javascript">
    $(document).ready( function () {
         $("#project-list").DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.11.4/i18n/es-mx.json"
            }
        });
    });
    $('.show_confirm').click(function(event) {
          var form =  $(this).closest("form");
          event.preventDefault();
          swal({
              title: "¿Esta seguro de eliminar esta reservación?",
              icon: "warning",
              buttons: true,
              dangerMode: true,
              buttons: ["Cancelar", "Eliminar"],
          })
          .then((willDelete) => {
            if (willDelete) {
              form.submit();
            }
          });
      });
</script>


<script>
    function updateEstatus(event) {
        let status = event.target.value;
        let id = event.target.getAttribute('data-id');

        $.ajax({
            type: "GET",
            dataType: "json",
            url: "{{route('update-status')}}",
            data: {
                'status': status,
                'id': id,
            },
            success: function(response) {
                Toast.fire({
                  icon: 'success',
                title: response.mensaje
                })
            }
        });
    }


    const Toast = Swal.mixin({
      toast: true,
      position: 'top-end',
      showConfirmButton: false,
      timer: 2000,
      timerProgressBar: true,
    })


</script>

@endsection

resources/views/reservaciones/plantillaContrato.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>

		<!-- Meta data -->
		<meta charset="UTF-8">
		<meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=0'>
		<meta content="Banquetes Cristy" name="author">


        <!--Favicon -->
		<link rel="icon" href="{{ asset('images/logo.png') }}" type="image/x-icon"/>
		<!-- Title -->
		<title>Banquetes Cristy</title>

		<style>
            *{
                font-family: Arial, Helvetica, sans-serif;
            }
            
            #logo{
                width: 15%;
                background-color: #fff;
            }

            #logo img{
                width: 100%;
            }

            p{
                text-align: justify;
            }
            span, .valoresDinamicos{
                text-decoration: underline;
                text-transform: uppercase;
                font-weight: bold;
            }
        </style>
	</head>


    <header>
        <div id="logo">
            <img src="{{ asset('images/logo_factura.png') }}" >
        </div>
        <div style="text-align: center;">
            <p style="text-align: center; line-height: 160%">PARA TODO EVENTO SOCIAL <br>
                QUINCEANERAS, BODAS <br>
                GRADUACIONES, BAUTIZOS</p>
        </div>
    </header>

	<body>
        <div id="informacionDeContacto">
            <table style="border: 0px; width: 800px;">
                <tr>
                    <td width="250px">Tel: 31 2 54 31</td>
                    <td width="250px">Celular: 834 138 7139</td>
                    <td width="250px">FB: Banquetes Cristy</td>
                </tr>
            </table>
        </div>

        <p>Sitio web: <a href="https://jmonrealr.wixsite.com/banquetes">https://jmonrealr.wixsite.com/banquetes</a> </p>

        <br>

        <h3 style="text-align: center">CONTRATO DE SERVICIOS</h3>

        <p>
            EL SENOR (A) <span>{{$booking->user->name}}</span> CON 
            @if ($profile)
                TELEFONO <span>{{$profile->phone_number}}</span>.    
            @else
                correo <span>{{$booking->user->email}}</span>.
            @endif
            
        </p>
        <p>
            COMO CONTRATANTE Y POR LA OTRA PARTE LA SRA. CRISTINA ROMERO VAZQUEZ, COMO PRESTADOR DEL SERVICIO, SE COMPROMETEN A RESPETAR LOS ACUERDOS ESTIPULADOS EN ESTE CONTRATO, DEJANDO CUBIERTO LOS SENALAMIENTOS DESCRITOS EN EL MISMO.
        </p>
        {{-- <p> --}}
            <table>
                <tr>
                    <td>PLATILLOS</td>
                    <td align="right" class="valoresDinamicos">{{$booking->quantity}}</td>
                </tr>
                <tr>
                    <td>MESEROS</td>
                    <td align="right" class="valoresDinamicos">
                        @if (
                                $services->contains(function ($service, $i) {
                                    if ($service['name'] == 'Mesero') {
                                        print($service->pivot->quantity);
                                        return true;
                                    }
                                })
                            )
                        @else
                            NO APLICA
                        @endif
                    </td>
                </tr>
                <tr>
                    <td>LOZA</td>
                    <td align="right" class="valoresDinamicos">
                        @if (
                                $services->contains(function ($service, $i) {
                                    if ($service['name'] == 'Loza') {
                                        print($service->pivot->quantity);
                                        return true;
                                    }
                                })
                            )
                        @else
                            NO APLICA
                        @endif
                    </td>
                </tr>
                <tr>
                    <td>DESECHABLES</td>
                    <td align="right" class="valoresDinamicos">SI APLICA</td>
                </tr>
            </table>
            {{-- PLATILLOS _________ ________________ <br>
            MESEROS __________ ________________ <br>
            LOZA ______________ ________________ <br>
            DESECHABLES _____ ________________ --}}
        {{-- </p> --}}
        <p>
            AL TERMINAR LA REUNION HABRA RECUENTO DE LA LOZA UTILIZADA, HACIENDO UN CARGO ADICIONAL POR LA FALTANTE.
        </p>
        {{-- <p> --}}
            <table>
                <tr>
                    <td>VASOS</td>
                    <td align="right" class="valoresDinamicos">{{$booking->quantity}} unidades</td>
                </tr>
                <tr>
                    <td>PLATOS</td>
                    <td align="right" class="valoresDinamicos">{{$booking->quantity}} unidades</td>
                </tr>
                <tr>
                    <td>TENEDORES</td>
                    <td align="right" class="valoresDinamicos">{{$booking->quantity}} unidades</td>
                </tr>
                <tr>
                    <td>CUCHILLOS</td>
                    <td align="right" class="valoresDinamicos">{{$booking->quantity}} unidades</td>
                </tr>
            </table>
            
            <br>

            FECHA <span>{{$booking->booking_date}}</span> HORA <span>{{$booking->booking_time}}</span> <br>
            DOMICILIO (SALON) <span>{{$booking->address->street_name}}. México, {{$booking->address->zip_code}} Cd Victoria, Tamaulipas.</span>
        {{-- </p> --}}
        <p>
            Al firmar este contrato el contratante cubrirá el costo del servicio en un 65%, el 35% restante, así como los utensilios faltantes deberán ser cubiertos al término de la reunión.
        </p>
        <br>
        <p style="text-align: center;">
            ________________________________ <br>
            Nombre y firma del contratante
        </p>
    </body>
</html>

resources/views/reservaciones/ver.blade.php
@extends('app')

@section('extra-css')
<style>
	#estimadoTotal{
		border:none;
		font-weight: bold;
		font-size: 22px;
		text-align: right;
		color: #7871df;
	}

	#mytable{
		border-collapse: collapse;
		border-radius: 15px;
		-webkit-box-shadow: 2px 2px 5px rgb(230, 228, 228);
 		-moz-box-shadow: 2px 2px 5px rgb(230, 228, 228);
	}

	#mytable thead th{
		color: #fff;
		background-color: #6c7ae0;
	}
	#mytable thead th:first-child{
		border-top-left-radius: 15px;
	}
	#mytable thead th:last-child{
		border-top-right-radius: 15px;
	}

	.filaSeparador{
		background-color: #f8f6ff;
	}
	.separador{
		border-top: 1px solid grey;
		font-weight: 500;
	}

	.img{
		width:80px;
		height:60px;
		/* width: 18%; */
		border-radius: 5px;
		margin-right: 2%;
	}
</style>

@endsection

@section('contenido')

        <!--Page header-->
	<div class="page-header d-xl-flex d-block">
		<div class="page-leftheader">
			<h4 class="page-title">Ver reservación #{{$booking->id}}</h4>
			<ul class="breadcrumb">
				<li class="mb-1 fs-16"><a href="/reservaciones">Reservaciones</a></li>
				<li class="text-muted mb-1 fs-16 ml-2 mr-2"> / </li>
				<li class="text-muted mb-1 fs-16">Ver reservación #{{$booking->id}}</li>
			</ul>
		</div>

	</div>
	<!--End Page header-->

	<!-- Fila detalles-->
	<div class="row">

		{{-- Tarjeta información --}}
	    <div class="col-xl-3 col-md-12 col-lg-12">
	        <div class="card">
				<div class="card-header d-xl-flex d-block">
					<div class="card-leftheader">
						<h4 class="card-title" id="impuestos">Detalles de la reservación</h4>
					</div>
				</div>
				<div class="card-body">
					<div class="row">
						<font style="vertical-align: inherit; font-weight:bold">Nombre del evento:</font>
						<span class="mb-2 fs-14">{{$booking->name}}</span>
					</div>
					<div class="row">
						<font style="vertical-align: inherit; font-weight:bold">Descripción:</font>
						<span class="mb-2 fs-14">{{$booking->description}}</span>
					</div>
					<div class="row">
						<font style="vertical-align: inherit; font-weight:bold">Cliente:</font>
						<span class="mb-2 fs-14">{{$booking->user->name}}</span>
					</div>
					<div class="row">
						<div class="col-6">
							<font style="vertical-align: inherit; font-weight:bold">Fecha:</font> <br>
							<span class="mb-2 fs-14">{{$booking->booking_date}}</span>
						</div>
						<div class="col-6">
							<font style="vertical-align: inherit; font-weight:bold">Hora:</font> <br>
							<span class="mb-2 fs-14">{{$booking->booking_time}}</span>
						</div>
					</div>
					<br>
					<div class="row">
						<div class="col-6">
							{{-- <button type="button" class="btn btn-primary">Contrato</button> --}}
							<a href="{{asset('/contracts' . '/CONTRACT-' . strval($booking->id).strval($booking->user->id) . '.pdf')}}" class="btn btn-primary" target="_blank">Contrato</a>
						</div>
						<div class="col-6">
							<a href="{{asset('/invoices' . '/FACT-' . strval($booking->id).strval($booking->user->id) . '.pdf')}}" class="btn btn-success" target="_blank">Factura</a>
							{{-- <button type="button" class="btn btn-success">Facturas</button> --}}
						</div>
					</div>
				</div>
	        </div>
	    </div>

		{{-- Tarjeta platillos --}}
		<div class="col-xl-9 col-md-12 col-lg-12">
			<div class="card">
				<div class="card-header d-xl-flex d-block">
					<div class="card-leftheader">
						<h4 class="card-title">Menú de la reservación</h4>
					</div>
				</div>

				<div class="card-body">
					{{-- Tabla platillos --}}
					<div class="row">
						<div class="table-responsive">
							<table class="table  text-wrap border-bottom table-borderless" id="mytable">
								<thead>
									<tr>
										<th class="border-bottom-0 text-center" width="60%">Nombre</th>
										<th class="border-bottom-0 text-center" width="15%" align="right">Cantidad</th>
										<th class="border-bottom-0 text-center" width="15%" align="right">Monto</th>
									</tr>
								</thead>
								<tbody id="lista_platillos">
									<tr class="filaSeparador">
										<td colspan="5" class="separador">Platillos</td>
									</tr>
		                            <tr>
		                                <td>
											<div class="d-flex">
												@if (isset($booking->booking->menu->url_img))
													<img class='img' src='{{asset($booking->booking->menu->url_img)}}'>
                        						@else
													<img class='img' src='{{asset($booking->booking->package->menu->url_img)}}'>
                        						@endif
												
												{{-- <span class="avatar-xl bradius mr-4" style="background-image: url('{{asset($booking->booking->menu->url_img)}}'"></span> --}}
												<div class="mr-3 mt-0 mt-sm-1 d-block">
													@if (isset($booking->booking->menu))
														<h6 class="mb-1 fs-14">{{$booking->booking->menu->name}}</h6>
														<p class="text-muted mb-0 fs-12">{{$booking->booking->menu->description}}</p>
                        							@else
														<h6 class="mb-1 fs-14">{{$booking->booking->package->description}}</h6>
                        							@endif
												</div>
											</div>
										</td>
		                                <td align="right">
		                                    <span>{{$booking->quantity}}</span>
		                                </td>
		                                <td align="center">
		                                    <span id="monto"></span>
		                                </td>
		                            </tr>
									@isset($services)
										<tr class="filaSeparador">
											<td colspan="5" id="separadorServicios" class="separador">Servicios</td>
										</tr>
										@foreach ($services as $service)
										<tr>
											<td>
												<div class="d-flex">
													{{-- <span class="avatar-xl bradius mr-4" style="background-image: url('{{asset($complement->url_image)}}'"></span> --}}
													<img class='img' src='{{asset($service->url_img)}}'>
													<div class="mr-3 mt-0 mt-sm-1 d-block">
														<h6 class="mb-1 fs-14">{{$service->name}}</h6>
														<p class="text-muted mb-0 fs-12">{{$service->description}}</p>
													</div>
												</div>
											</td>
											<td align="right">
												<span>{{$service->pivot->quantity}}</span>
											</td>
											<td align="center">
												<span class="montoServicio"></span>
											</td>
										</tr>
										@endforeach
									@endisset
									@isset($complements)
										<tr class="filaSeparador">
											<td colspan="5" id="separadorComplemento" class="separador">Complementos</td>
										</tr>
										@foreach ($complements as $complement)
										@isset($complement)
										<tr>
											<td>
												<div class="d-flex">
													{{-- <span class="avatar-xl bradius mr-4" style="background-image: url('{{asset($complement->url_image)}}'"></span> --}}
													<img class='img' src='{{asset($complement->url_image)}}'>
													<div class="mr-3 mt-0 mt-sm-1 d-block">
														<h6 class="mb-1 fs-14">{{$complement->name}}</h6>
														<p class="text-muted mb-0 fs-12">Sin descripción</p>
													</div>
												</div>
											</td>
											<td align="right">
												<span>1</span>
											</td>
											<td align="center" class="text-success font-weight-bold">¡Gratis!</td>
										</tr>
										@endisset
										@endforeach
									@endisset
		                        </tbody>
								<tfoot>
									<tr>
										<td></td>
										<td align="right" width="15%"><h6 class="mb-1 fs-17 text-muted">Total:</h6></td>
										<td width="25%" align="center"><input type="text" class="form-control mb-md-1 mb-5 fs-17 text-center" id="estimadoTotal" name="total" readonly></td>
									</tr>
								</tfoot>
		                    </table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Row-->

	<!-- Fila ubicacion y contacto-->
	<div class="row">
		<div class="col-xl-12 col-md-12 col-lg-12">
	        <div class="card">
				<div class="card-header d-xl-flex d-block">
					<div class="card-leftheader">
						<h4 class="card-title" id="impuestos">Ubicación del evento</h4>
					</div>
				</div>
				<div class="card-body">
					<div class="row">

					</div>
					<div class="row">
						<div class="col-5">
							<div class="d-flex">
								<span class="avatar-xl mr-1">
									<i class="feather feather-map-pin text-primary"></i>
								</span>
								<div class="mr-3 mt-0 mt-sm-1 d-block">
									<font style="vertical-align: inherit; font-weight:bold">Dirección:</font> <br>
									<span class="mb-2 fs-14">{{$booking->address->street_name}}. México, {{$booking->address->zip_code}} Cd Victoria, Tamaulipas. <br> {{$booking->address->description}}</span>
								</div>
							</div>
						</div>
						<div class="col-4">
							<div class="d-flex">
								<span class="avatar avatar-md brround mr-3" style="background-image: url({{asset('images/usuario.png')}}"></span>
								<div class="mr-3 mt-0 mt-sm-1 d-block">
									<font style="vertical-align: inherit; font-weight:bold">Cliente:</font> <br>
									<span class="mb-2 fs-14">{{$booking->user->name}}</span>
								</div>
							</div>
						</div>
						<div class="col-3">
							<div class="d-flex">
								<span class="avatar-xl" style="margin-right: -15px;">
									<i class="feather feather-mail text-primary"></i>
								</span>
								<div class="mr-3 mt-0 mt-sm-1 d-block">
									<font style="vertical-align: inherit; font-weight:bold">Correo electrónico:</font> <br>
									<span class="mb-2 fs-14">{{$booking->user->email}}</span>
								</div>
							</div>
							{{-- <font style="vertical-align: inherit; font-weight:bold">Telefono:</font> <br>
							<span class="mb-2 fs-14">834 171 1100</span> --}}
						</div>
					</div>
				</div>
                <div class="card-footer text-right">
                        <a role="button" class="btn btn-outline-dark" href="{{ url()->previous() }}">
					        <i class="feather feather-corner-down-left sidemenu_icon"></i>
					        Regresar
				        </a>
                    </div>
	        </div>
	    </div>
	</div>
@endsection



@section('extra-script')
<script>
	$(function() {
		window.escribirTotal = function(){
			let monto = document.getElementById('monto');
			let total = document.getElementById('estimadoTotal');

			monto.innerText = numberToMoney({{$booking->subtotal}});
			total.setAttribute('value', numberToMoney({{$booking->total}}));
		}
		escribirTotal();
	});

	$(function() {
		window.escribirMontoServicios = function(){
			let casillasMonto = document.getElementsByClassName('montoServicio');
			let servicios = @json($services);

			for (let i = 0; i < casillasMonto.length; i++) {
				casillasMonto[i].innerText = numberToMoney(servicios[i]['pivot']['quantity'] * servicios[i]['price']);
			}
		}
		escribirMontoServicios();
	});

	/*
		Da formato de moneda a String
	*/
	function numberToMoney(value) {
		const formatterDolar = new Intl.NumberFormat('en-US', {
    		style: 'currency',
       		currency: 'USD'
     	});
		if (isNaN(value)) {
			value = 0;
		}

		return formatterDolar.format(value);
	}
</script>

@endsection