routes/web.php
<?php

use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Employee\ComplementController;
use App\Http\Controllers\Employee\InventoryController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\Employee\PackageController;
use App\Http\Controllers\Employee\ServiceController;
use App\Http\Controllers\Employee\StatusController;
use App\Http\Controllers\Employee\MenuController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PDFController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Website\MenuController as WebsiteMenuController;
use Illuminate\Support\Facades\Route;

// Route::get('/', function () {
//     return view('dashboard.dashAdmin', [DashboardController::class, 'dashboardAdmin']);
// });



Route::get('/reservar', [BookingController::class, 'create'])->name('website.reservar');
Route::post('/reservar', [BookingController::class, 'store'])->name('reservar.store');

Route::get('/factura', function () {
    return view('facturas.plantilla-pdf');
});

Route::get('/inicio', function () {
    return view('website/principal');
})->name('website');

#Visualizar vista verificar correo
#Route::get('/verify', function () {
    #return view('auth/verify');
#})->name('website');
#

Route::controller(MenuController::class)->group(function () {
    Route::match(array('GET', 'POST'), 'website/menu', [WebsiteMenuController::class,'index'])->name('website.menu');
    Route::match(array('GET', 'POST'), 'website/menu/search', [WebsiteMenuController::class,'search'])->name('website.menu.search');
    Route::match(array('GET', 'POST'), 'website/menu/category', [WebsiteMenuController::class,'searchByCategory'])->name('website.menu.category');
});


//Route::get('menu', function () {
//    return view('menu.index');
//});
//Route::get('menu/crear', function () {
//    return view('menu.crear');
//});
//Route::get('menu/ver', function () {
//    return view('menu.ver');
//});



//Route::resource('inventario', InventoryController::class);

//Route::get('inventario/{id}', [InventoryController::class, 'show']);



//Route::get('configuracion', function () {
//    return view('configuracion.index');
//});

// Route::get('create-pdf-file', [PDFController::class, 'index']);

//Authenticated Routes
Route::middleware(['auth'])->group( function () {
    Route::get('/profile/edit', 'App\Http\Controllers\ProfileController@edit')->name('profile.edit');
    Route::get('/profile/change-password', 'App\Http\Controllers\ProfileController@change_password')->name('profile.change-password');
    Route::get('/profile', 'App\Http\Controllers\ProfileController@index')->name('profile.index');
    Route::patch('/profile', 'App\Http\Controllers\ProfileController@update')->name('profile.update');
});

//Admin Routes
Route::prefix('admin')->name('admin.')->middleware(['auth', 'auth.isAdmin'])->group( function () {
    Route::resource('/users', UserController::class);
});

//Employee routes
Route::middleware(['auth', 'verified', 'auth.isEmployee'])->group( function () {
    //TODO: Empleados
    Route::get('/empleados', function () {
        return view('empleados.index');
    });
    Route::get('/empleados/crear', function () {
        return view('empleados.crear');
    });
    //TODO: Clientes
    Route::get('/clientes', function () {
        return view('clientes.index');
    });
    Route::get('/clientes/crear', function () {
        return view('clientes.crear');
    });
    Route::get('/clientes/ver', function () {
        return view('clientes.ver');
    });
    Route::get('/reportes', function () {
        return view('reportes.index');
    });
    Route::get('/updateStatus', [BookingController::class, 'updateStatus'])->name('update-status');

    Route::get('/dashboard', [DashboardController::class, 'dashboardAdmin']);

    Route::post('create-pdf-file', [PDFController::class, 'index']);

    Route::resource('/reservaciones', BookingController::class);
    Route::resource('/inventario', InventoryController::class);
    Route::resource('/status', StatusController::class);
    Route::resource('/services',ServiceController::class);
    Route::resource('/menus', MenuController::class);
    Route::resource('/packages', PackageController::class);
    Route::resource('/complements',ComplementController::class);
});

//Customer routes
Route::middleware(['auth', 'auth.isCustomer'])->group( function () {
    Route::get('/dashboard/customer', [DashboardController::class, 'dashboardCliente'])->name('dashboardCustomer');
});

//Default routes

Route::get('/', [HomeController::class, 'index']);

resources/views/inventario/crear.blade.php
@extends('app')

@section('contenido')

@include('sweetalert::alert')
<!--Page header-->
<div class="page-header d-xl-flex d-block">
	<div class="page-leftheader">
		@if(is_null($inventory))
		<h4 class="page-title">Agregar producto</h4>
		@else
		<h4 class="page-title">Editar Producto {{$inventory->id}}</h4>
		@endif
		<ul class="breadcrumb">
			<li class="mb-1 fs-16"><a href="{{ route('inventario.index') }}">Inventario</a></li>
			<li class="text-muted mb-1 fs-16 ml-2 mr-2"> / </li>
			@if(is_null($inventory))
			<li class="text-muted mb-1 fs-16"> Agregar producto</li>
			@else
			<li class="text-muted mb-1 fs-16">Editar Producto</li>
			@endif
		</ul>
	</div>
</div>
<!--End Page header-->

<!-- ------------------------------------------------------------------------- -->
<!-- Row -->
<div class="row">
	<div class="col-xl-12 col-md-12 col-lg-12">
		<div class="card">
		@if(is_null($inventory))
		<form action="{{ route('inventario.store') }}" method="POST" enctype="multipart/form-data">
		@else
		<form action="{{ route('inventario.update', $inventory->id) }}" method="POST" enctype="multipart/form-data">
			@method('PUT')
		@endif
            @csrf
			<div class="card-body">
				<h4 class="mb-5 font-weight-semibold">Información básica</h4>
				<div class="row">
					<div class="col-sm-3">
						<!--left col-->
						<div class="text-center user-pic">
							@if(is_null($inventory) or is_null($inventory->url_image) or !file_exists(public_path() .'/'. $inventory->url_image))
							<img src="https://cdn2.iconfinder.com/data/icons/food-drinks-vol-3/48/105-512.png" class="avatar-xxl rounded-circle mb-1" alt="Foto producto" name="image" id="image">
							@else
							<img src="{{ asset($inventory->url_image) }}" class="avatar-xxl rounded-circle mb-1" alt="Foto producto" name="image" id="image">
							@endif
							<h6>Suba una imagen...</h6>
							<label class="mb-0">
								<span class="btn ripple btn-primary">
									<i class="feather feather-upload sidemenu_icon"></i>
									Examinar <input type="file" class="file-browserinput" style="display: none;" accept="image/*" name="url_image" id="url_image" onchange="previewImage(event)">
								</span>
							</label>
						</div>
					</div>
					<div class="col-sm-9">
						<!-- Main col -->
						<div class="row">
							<div class="col-xs-3">
								<div class="form-group">
									<label class="form-label" for="name">
										Nombre*
									</label>
									@if(is_null($inventory))
									<input class="form-control @error('name') is-invalid @enderror" type="text" placeholder="Ingresa el nombre del producto" name="name" id="name" maxlength="55">
									@else
									<input class="form-control @error('name') is-invalid @enderror" type="text" placeholder="Ingresa el nombre del producto" name="name" id="name" value="{{$inventory->name}}" maxlength="55">
									@endif
                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            {{ $message }}
                                        </span>
                                    @enderror
								</div>
							</div>
							<div class="col-xs-3">
								<div class="form-group">
									<label class="form-label" for="quantity">
										Cantidad*
									</label>
									@if(is_null($inventory))
									<input class="form-control @error('quantity') is-invalid @enderror" type="number" placeholder="100" min="0" name="quantity" id="quantity" min="1" max="500">
									@else
									<input class="form-control @error('quantity') is-invalid @enderror" type="number" placeholder="100" min="0" name="quantity" id="quantity" min="1" max="500" value="{{$inventory->quantity}}">
									@endif
                                    @error('quantity')
                                        <span class="invalid-feedback" role="alert">
                                            {{ $message }}
                                        </span>
                                    @enderror
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-11">
								<div class="form-group">
									<label class="form-label" for="description">
										Descripción*
									</label>
									@if(is_null($inventory))
									<input type="text" class="form-control @error('description') is-invalid @enderror" name="description" id="description" placeholder="Ingrese la descripción del producto"  title="Ingrese la descripción del producto" maxlength="250">
									@else
									<input type="text" class="form-control @error('description') is-invalid @enderror" name="description" id="description" placeholder="Ingrese la descripción del producto"  title="Ingrese la descripción del producto" value="{{$inventory->description}}" maxlength="250">
									@endif
                                    @error('description')
                                        <span class="invalid-feedback" role="alert">
                                            {{ $message }}
                                        </span>
                                    @enderror
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="card-footer text-right">
				<a role="button" class="btn btn-outline-dark" href="{{ url()->previous() }}">
					<i class="feather feather-corner-down-left sidemenu_icon"></i>
					Regresar
				</a>
				<button type="submit" class="btn btn-primary">
					<i class="feather feather-save sidemenu_icon"></i>
					Guardar
				</button>
			</div>
		</form>
		</div>
	</div>
</div>
<!-- End Row-->
@endsection

<script type="text/javascript">
	const previewImage = e => {
		const preview = document.getElementById('image');
		preview.src = URL.createObjectURL(e.target.files[0]);
		preview.onload = () => URL.revokeObjectURL(preview.src);
	};
</script>



@section('extra-script')
	<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
	<script src="{{ asset('js/confirmExit.js') }}"></script>
	<script src="{{ asset('js/characterCounter.js') }}"></script>
@endsection

resources/views/inventario/index.blade.php
@extends('app')

@section('extra-css')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.4/css/dataTables.bootstrap5.min.css"/>
@endsection

@section('contenido')

<!--Page header-->
<div class="page-header d-xl-flex d-block">
    <div class="page-leftheader">
        <h4 class="page-title">Inventario</h4>
    </div>
    <div class="page-rightheader ml-md-auto">
        <div class="align-items-end flex-wrap my-auto right-content breadcrumb-right">
            <div class="btn-list">
                <a href="{{ route('inventario.create') }}" class="btn btn-primary mr-3">
                    <i class="feather  feather-plus sidemenu_icon"></i>
                    Agregar producto</a>
            </div>
        </div>
    </div>
</div>
<!--End Page header-->

    <!-- Row -->
    <div class="row">
        @include('sweetalert::alert')
    	<div class="col-xl-12 col-md-12 col-lg-12">
    		<div class="card">
                <div class="card-header  border-0">
                    <h4 class="card-title">Lista de Inventario</h4>
                </div>
    			<div class="card-body">
                <div class="table-responsive">
                    <table class="table table-vcenter text-wrap table-bordered border-bottom" id="project-list">
						<thead>
							<tr>
                                <th class="border-bottom-0">ID</th>
                                <th class="border-bottom-0">Nombre</th>
                                <th class="border-bottom-0">Cantidad</th>
                                <th class="border-bottom-0">Descripción</th>
                                <th class="border-bottom-0">Creado en</th>
                                <th class="border-bottom-0">Acciones</th>
							</tr>
						</thead>
                        <tbody>
                            @isset($inventory)
                                    @foreach($inventory as $inv)
                                        <tr>
                                            <td>{{ $inv->id }}</td>
                                            <td>
                                                <div class="d-flex">
                                                    @if (is_null($inv->url_image))
                                                        <span class="avatar avatar-md brround mr-3" style="border-color: transparent; background-color:transparent; background-image: url({{'https://cdn2.iconfinder.com/data/icons/food-drinks-vol-3/48/105-512.png'}}"></span>
                                                    @else
                                                    <span class="avatar avatar-md brround mr-3" style="border-color: transparent; background-color:transparent; background-image: url({{asset($inv->url_image)}}"></span>
                                                    @endif
                                                    <div class="mt-0 mt-sm-2 d-block">
                                                        <h6 class="mb-1 fs-17">{{ $inv->name }}</h6>
                                                    </div>
                                                </div>
                                            </td>
                                            <td align="right">{{ $inv->quantity }}</td>
                                            <td>{{ $inv->description }}</td>
                                            <td>{{ date('d/M/Y', strtotime( $inv->created_at)) }}</td>
                                            <td>
                                                <div class="d-flex">
                                                    <a href="{{ route('inventario.show', $inv->id) }}" class="action-btns1" data-toggle="tooltip" data-placement="top" title="Ver"><i class="feather feather-eye text-primary"></i></a>
                                                    <a href="{{route('inventario.edit', $inv->id)}}" class="action-btns1" data-toggle="tooltip" data-placement="top" title="Editar"><i class="feather feather-edit-2  text-success"></i></a>
                                                    <form action="{{route('inventario.destroy', $inv->id)}}" method="post">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button class="action-btns1 feather feather-trash-2 text-danger show_confirm" data-toggle="tooltip" data-placement="top" title="Eliminar" type="submit"></button>
                                                    </form>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                            @endisset
                        </tbody>
                    </table>
					</div>
    			</div>
    		</div>
    	</div>
    </div>
    <!-- End Row-->
@endsection

@section('extra-script')
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.11.4/js/dataTables.bootstrap5.min.js"></script>
{{--"url": "//cdn.datatables.net/plug-ins/1.11.3/i18n/es-MX.json"//ES = 90% and MX 88% //cdn.datatables.net/plug-ins/1.11.4/i18n/es-MX.json--}}
<script type="text/javascript">
    $(document).ready( function () {
         $("#project-list").DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.11.4/i18n/es-mx.json"
            }
        });
    });
    $('.show_confirm').click(function(event) {
          var form =  $(this).closest("form");
          event.preventDefault();
          swal({
              title: "¿Esta seguro de eliminar este producto?",
              icon: "warning",
              buttons: true,
              dangerMode: true,
              buttons: ["Cancelar", "Eliminar"],
          })
          .then((willDelete) => {
            if (willDelete) {
              form.submit();
            }
          });
      });
</script>

@endsection

resources/views/inventario/ver.blade.php
@extends('app')

@section('contenido')

<!--Page header-->
<div class="page-header d-xl-flex d-block">
	<div class="page-leftheader">
		<h4 class="page-title">Ver Producto {{$inventory->id}}</h4>
		<ul class="breadcrumb">
			<li class="mb-1 fs-16"><a href="/inventario">Inventario</a></li>
			<li class="text-muted mb-1 fs-16 ml-2 mr-2"> / </li>
			<li class="text-muted mb-1 fs-16">Ver Producto</li>
		</ul>
	</div>

</div>
<!--End Page header-->

<!-- Row -->
<div class="row">
	<div class="col-xl-3 col-md-12 col-lg-12">
		<div class="card">
			<div class="card-header d-xl-flex d-block">
				<div class="card-leftheader">
					<h4 class="card-title" id="impuestos">Información del Producto</h4>
				</div>
			</div>
			<div class="card-body text-center">
				<div class="user-pic">
					@if(is_null($inventory->url_image))
					<img src="https://cdn2.iconfinder.com/data/icons/food-drinks-vol-3/48/105-512.png" alt="user-img" class="avatar-xxl rounded-circle mb-1" alt="Foto producto">
					@else
					<img src="{{ asset($inventory->url_image) }}" alt="user-img" class="avatar-xxl rounded-circle mb-1" alt="Foto producto">
					@endif
				</div>
				<div class="col-sm-12">
					<div class="row">
						<font style="vertical-align: inherit; font-weight:bold">Nombre</font>
						<span class="mb-2 fs-14">{{$inventory->name}}</span>
					</div>
					<div class="row">
						<font style="vertical-align: inherit; font-weight:bold">Descripción</font>
						<span class="mb-2 fs-14">{{$inventory->description}}</span>
					</div>
					<div class="row">
						<font style="vertical-align: inherit; font-weight:bold">Cantidad</font>
						<span class="mb-2 fs-14">{{$inventory->quantity}}</span>
					</div>
				</div>
			</div>
            <div class="card-footer text-right">
                <a role="button" class="btn btn-outline-dark" href="{{ url()->previous() }}">
                    <i class="feather feather-corner-down-left sidemenu_icon"></i>
                    Regresar
                </a>
            </div>
		</div>
	</div>
</div>
<!-- End Row-->
@endsection